const products = [
    {
        id: 1,
        name: 'Caramen latte',
        alt: 'caramel-latte',
        image: '../public/images/sp-1-caramel-latte.jpg',
        price: {
            S: 30000,
            M: 35000,
            L: 40000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 2,
        name: 'Cà phê mocha',
        alt:'mocha-nong',
        image: '../public/images/sp-2-cafe-mocha-nong.jpg',
        price: {
            S: 25000,
            M: 30000,
            L: 35000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 3,
        name: 'Macchiato',
        alt:'epresso-macchiato',
        image: '../public/images/sp-3-epresso-macchiato.jpg',
        price: {
            S: 25000,
            M: 30000,
            L: 35000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 4,
        name: 'ESPRESSO MACCHIATO',
        alt:'ESPRESSO-MACCHIATO',
        image: '../public/images/sp-4.jpg',
        price: {
            S: 40000,
            M: 45000,
            L: 50000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 5,
        name: 'CHOCOLATE MOCHA',
        alt:'CHOCOLATE MOCHA',
        image: '../public/images/sp-5.jpg',
        price: {
            S: 50000,
            M: 55000,
            L: 60000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 6,
        name: 'CARAMEL MACCHIATO',
        alt:'CARAMEL-MACCHIATO',
        image: '../public/images/sp-6.jpg',
        price: {
            S: 50000,
            M: 55000,
            L: 60000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 7,
        name: 'cà phê AMERICANO',
        alt:'coffee-AMERICANO',
        image: '../public/images/sp-7.jpg',
        price: {
            S: 40000,
            M: 45000,
            L: 50000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 8,
        name: 'latte đá',
        alt:'latte-da',
        image: '../public/images/sp-8.jpg',
        price: {
            S: 30000,
            M: 35000,
            L: 40000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 9,
        name: 'CAPPUCCINO',
        alt:'CAPPUCCINO',
        image: '../public/images/sp-9.jpg',
        price: {
            S: 40000,
            M: 45000,
            L: 50000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 10,
        name: 'Freeze mocha',
        alt:'Freeze-mocha',
        image: '../public/images/sp-10.jpg',
        price: {
            S: 45000,
            M: 50000,
            L: 55000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 11,
        name: 'Latte vani',
        alt:'Latte-vani',
        image: '../public/images/sp-11.jpg',
        price: {
            S: 50000,
            M: 55000,
            L: 60000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 12,
        name: 'Latte GINGERBREAD',
        alt:'Latte-GINGERBREAD',
        image: '../public/images/sp-12.jpg',
        price: {
            S: 50000,
            M: 55000,
            L: 60000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 13,
        name: 'Bạc xỉu',
        alt:'bac-xiu',
        image: '../public/images/sp-13-bac-xiu.jpg',
        price: {
            S: 30000,
            M: 35000,
            L: 40000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 14,
        name: 'Trà đào',
        alt:'tra-dao',
        image: '../public/images/sp-14-tradao.jpg',
        price: {
            S: 30000,
            M: 35000,
            L: 40000,
        },
        type: 'tea',
        quantity: 1,
    },
    {
        id: 15,
        name: 'Freeze Matcha',
        alt:'Freeze-Matcha',
        image: '../public/images/sp-15-freeze-matcha.jpg',
        price: {
            S: 40000,
            M: 45000,
            L: 50000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 16,
        name: 'Đen đá',
        alt:'den-da',
        image: '../public/images/sp-16-denda.jpg',
        price: {
            S: 20000,
            M: 25000,
            L: 30000,
        },
        type: 'coffee',
        quantity: 1,
    },
    {
        id: 16,
        name: 'Đen đá',
        alt:'den-da',
        image: '../public/images/sp-16-denda.jpg',
        price: {
            S: 20000,
            M: 25000,
            L: 30000,
        },
        type: 'coffee',
        quantity: 1,
    },
]